name: chat-less

services:
  chat-less-client:
    image: holyshiznicks/chat-less-client:latest
    restart: unless-stopped
    ports:
      - '5173:80'
  chat-less-server:
    image: holyshiznicks/chat-less-server:latest
    restart: unless-stopped
    ports:
      - '4000:4000'
    volumes:
      - ./server/logs:/app/logs:rw        #Mount the host's server logs so that logs written in the container can persist
      - /etc/timezone:/etc/timezone:ro    #Mount the host's timezone settings
      - /etc/localtime:/etc/localtime:ro  #Mount the host's localtime settings